### ISSUE TITLE
Tên file

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#1]
https://github.com/Duong100194/Laravel_Pr/blob/5f01ee340eed21329743a660d5d32f7e629865f7/BaitapLaravel_User/app/Http/Controllers/CreateUserController.php#L12

Tên file của blade hay directory, em đều nên dùng kiểu dấu gạch trừ để cách e nhé:
Sẽ thành ra thế này: **[create-user].**
Để In hoa ko sai, nhưng ko chuẩn.
Cách đặt in Hoa ngày xưa a cũng làm, nhưng no ko đẹp nên a đã chuyển qua dấu gạch trừ rồi.

**Comment by Duong100194** [comment]
done
