### ISSUE TITLE
Nâng cấp validate

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#25]
https://github.com/Duong100194/Laravel_Pr/blob/3f7ba4057fc9135e97a78e7d39f84fc3b6053f30/BaitapLaravel_User/app/Http/Controllers/UserController.php#L65

Thay vì validate tại controller, e đổi sang dùng request.

Dùng câu lệnh [ php artisan make:request <tên:UserRequest>], nó sẽ tạo cho e 1 request.
Xong sau đó, e mang hết toàn bộ rule của e vào request, đặt trong hàm:
public function rules(){
 //rules
}
Sau đó e để trong controller:
public function update(UserRequest $request)
{
 //cac xu ly ben trong.
 //Vì request chúng ta đã tạo, nó thừa kế toàn bộ từ Object Request, nên những gì có trong Request nguyên thủy sẽ có trong 
 //Request chúng ta đã tạo, và dc nâng cấp lên theo tùy chỉnh của mình.
 //Xử lý: trước khi vào controller của ta, nó sẽ nhảy vào UserRequest và xác nhận các field ta đã định nghĩa validate
 //Làm như vậy ko khác gì so với code cũ e viết, nhưng nó sẽ Logic hơn là: trước khi xử lý code trong controller ta sẽ validate nó, 
 //chứ ko phải vào controller rồi mới validate. Ngoài ra, sẽ giúp code của Controller dc giảm bớt, vì các xử lý thường được đưa 
 //vào controller, nên giảm dc càng nhiều càng tốt
}

**Comment by Duong100194** [comment]
done
