### ISSUE TITLE
Nâng cấp xử lý update insert

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#26]
https://github.com/Duong100194/Laravel_Pr/blob/3f7ba4057fc9135e97a78e7d39f84fc3b6053f30/BaitapLaravel_User/app/Http/Controllers/UserController.php#L71

Yêu cầu, ta sẽ có khả năng rollback lại dữ liệu nếu xảy ra lỗi khi insert hay update.

Khi insert hay update, nếu viết code như thế này, xảy ra lỗi, sẽ ko thể rollback dữ liệu.
Vì vậy thêm vào transaction trước nó, sẽ giúp cho ta có thể rollback dc dữ liệu.
Thí du:
 - $user = User::insert(); //insert xong trã về user đã dc insert
 - Post::insert(['post_name' => 'test', 'user_id' => $user->id]); //e sẽ thêm post vào theo user ở trên.
 Thí dụ bên trên, ta đặt 2 xử lý đó chung 1 controller, nó thêm user xong, sẽ dựa theo user đó mà thêm post cho user đó.
 E thử tưởng tượng, User đó ta thêm dc, nhưng post ko thêm dc, vậy là đã nãy ra 1 user thừa cho 1 post. Và nó ko tốt.

**Nhưng nếu ta chuyển wa dùng thế này:**
  DB::transaction(function() {
    $user = User::insert();
    Post::insert(['post_name' => 'test', 'user_id' => $user->id]);
  })
Dù lỗi nãy ra ở post, nhưng do lỗi, và ta đang ở trong 1 transaction, do đó, DB sẽ tự động biết rollback toàn bộ dữ liệu đã xảy ra lỗi -> Xóa luon user đã tạo, xóa cả post đã bị lỗi.

Khái niệm cần đọc sơ qua: Database transaction.
Nói sơ qua về transaction, nếu những xử lý dc đặt trong 1 transaction, tất cả sẽ dc sao lưu nếu toàn bộ chạy trơn tru.
Nhưng nếu xảy ra lỗi, nó sẽ rollback lại toàn bộ xử lý đó, giúp cho dữ liệu của ta ko bị hỗn loạn khi xảy ra lỗi

**Comment by Duong100194** [comment]
done
