### ISSUE TITLE
Em cải tiến phần view.

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#27]
Hiện tại, view-list, view-insert, view-update nó đang có chung 1 format view html.
Yêu cầu, em gom các phần head, body chung lại thành 1 layout, cho 3 cái view kia thừa kế nó.

Mẫu:
Tạo layout:
 - layout.blade.php
  - Đặt @yield('tên-cần-đặt') vào nơi code sẽ thay đổi
  - Tại view-list, view-insert, view-update:
    - @extends('layouts')
      @section('tên-đã-đặt-ở-yield')
         {{--source của view đó--}}
      @endsection
Với động tác làm như thế, e sẽ ko cần phải viết wá nhiều code nhưng lại hoàn toàn chung nội dung

**Comment by Duong100194** [comment]
done
