### ISSUE TITLE
Thục đầu hàng

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#29]
https://github.com/Duong100194/Laravel_Pr/blob/213e394e7c157dd8f761011a6d7fb8f890a0925b/BaitapLaravel_User/app/Http/Controllers/UserController.php#L55

Từ dòng 55 đến 61, bên trong 1 block code, em bôi đen rồi bấm tab cho nó, làm như vậy e sẽ biết dc cái nào ở ngoài, cái nào ở trong, code sẽ mạch lạc hơn rất nhiều, dễ đọc nữa.

**Comment by Duong100194** [comment]
done
