### ISSUE TITLE
Dấu cách trước và sau dấu =

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#5]
https://github.com/Duong100194/Laravel_Pr/blob/b229657661bd6c16b8bb925898172bfc84ec8d8e/BaitapLaravel_User/app/Http/Controllers/UsersController.php#L53

Hầu hết các dòng code của em, nó không đảm bảo dc dấu cách trước và sau dấu =.
Code sẽ khó nhìn. 
Từ nay về sau, trước và sau tất cả các toán tử như: [<, >, =, /, *, +, -....] phải đảm bảo dấu cách trước và sau nó nhé

**Comment by Duong100194** [comment]
done
