### ISSUE TITLE
Đặt dấu cách

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#7]
https://github.com/Duong100194/Laravel_Pr/blob/b229657661bd6c16b8bb925898172bfc84ec8d8e/BaitapLaravel_User/app/Http/Controllers/UsersController.php#L49

Luôn luôn đặt dấu cách ở sau dấu phẩy
-> (StroreUserRequest $request, $id).
Các nơi khác như khai báo mảng: ['test1', 'test2', 'test3'] củng phải đặt dấu cách sau dấu phẩy

**Comment by Duong100194** [comment]
done
