### ISSUE TITLE
Lưu ý dùng Eloquent

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#8]
https://github.com/Duong100194/Laravel_Pr/blob/b229657661bd6c16b8bb925898172bfc84ec8d8e/BaitapLaravel_User/app/Http/Controllers/UsersController.php#L18

Lưu ý, khi dùng DB::table() em sẽ loại bỏ hết toàn bộ các tiện ích của Eloquent.
Nên chỉ gọi khi phải dùng các trường hợp select sql phức tạp.
Còn chỉ dùng dể Select thế này, hãy dùng Eloquent model nhé.
Khi học viết nhiều cách là tốt.

Nên hhi nhớ sau này về việc này

**Comment by Duong100194** [comment]
Done
