### ISSUE TITLE
SQL trùng

### ISSUE THREAD

**Issue by ncttu218** [Duong100194/Laravel_Pr#9]
https://github.com/Duong100194/Laravel_Pr/blob/b229657661bd6c16b8bb925898172bfc84ec8d8e/BaitapLaravel_User/app/Http/Controllers/UsersController.php#L46

Ở dòng này em đã find 1 lần rồi.
Tại sao dòng dưới em lại gọi 1 lần nữa?!
Đây chỉ là học nên viết nhiều cách thì rất tốt.
Nhưng chú ý đừng để 2 dòng code chạy cùng 1 hành động thế này, sẽ rất tốt tài nguyên server

**Comment by Duong100194** [comment]
done
